<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomObject</name>
   <tag></tag>
   <elementGuidId>c3742c55-fd89-4bab-972e-d8c5689f2697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${xpath}</value>
      <webElementGuid>9034cd90-601d-44e2-b287-eaf169b4cda6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
