<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IPRecordType</name>
   <tag></tag>
   <elementGuidId>ae9fa4b6-a14f-4d24-9bab-e4500502dedd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@class='data2Col']/div[@class='requiredInput']/select/option[text()='IP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${value}</value>
      <webElementGuid>1eb532e6-068a-4477-94d3-eb7b274d55a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
